// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RequestPigeon.Infrastructure.Persistence;

#nullable disable

namespace RequestPigeon.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(RequestPigeonDbContext))]
    partial class RequestPigeonDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RequestPigeon.Domain.Entities.Attachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime?>("LastModification")
                        .HasColumnType("datetime2(7)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.HasIndex("Extension");

                    b.ToTable("Attachments", (string)null);
                });

            modelBuilder.Entity("RequestPigeon.Domain.Entities.AuthenticationSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(7)");

                    b.Property<DateTime?>("LastModification")
                        .HasColumnType("datetime2(7)");

                    b.Property<int?>("LockoutAfterXFailed")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("LockoutTime")
                        .HasColumnType("time");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.ToTable("AuthenticationSettings", (string)null);
                });

            modelBuilder.Entity("RequestPigeon.Domain.Entities.Claim", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("DefaultValue")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime?>("LastModification")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("ValueType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Claims", (string)null);
                });

            modelBuilder.Entity("RequestPigeon.Domain.Entities.DemoReseedLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<DateTime?>("LastModification")
                        .HasColumnType("datetime2(7)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2(0)");

                    b.Property<Guid?>("StartedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("Succeeded")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CompletedAt");

                    b.HasIndex("StartedAt");

                    b.HasIndex("StartedByUserId");

                    b.ToTable("DemoReseedLogs", (string)null);
                });

            modelBuilder.Entity("RequestPigeon.Domain.Entities.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DocumentId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(7)");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime?>("LastModification")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<Guid>("RequesterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("TextContent")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("TextMessage")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.HasKey("Id");

                    b.HasIndex("DateTime");

                    b.HasIndex("RequesterId");

                    b.HasIndex("Type");

                    b.HasIndex("Type", "Status");

                    b.ToTable("Documents", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("RequestPigeon.Domain.Entities.DocumentApprovalRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AllowSelfApproval")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("DecisionMakerType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<Guid>("DocumentSettingsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastModification")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("RoleOrClaimName")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("StepOrder")
                        .HasColumnType("int");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("DocumentSettingsId", "StepOrder");

                    b.HasIndex("DecisionMakerType", "UserId", "RoleOrClaimName");

                    b.ToTable("DocumentApprovalRules", (string)null);
                });

            modelBuilder.Entity("RequestPigeon.Domain.Entities.DocumentApprovalStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApproverId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(7)");

                    b.Property<DateTime?>("DateTimeDecision")
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime?>("DateTimeIssued")
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("Decision")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastModification")
                        .HasColumnType("datetime2(7)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<int>("StepOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApproverId", "Status");

                    b.HasIndex("DocumentId", "StepOrder");

                    b.ToTable("DocumentApprovalSteps", (string)null);
                });

            modelBuilder.Entity("RequestPigeon.Domain.Entities.DocumentSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("DefaultTextContent")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("Header")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime?>("LastModification")
                        .HasColumnType("datetime2(7)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.HasKey("Id");

                    b.HasIndex("Type")
                        .IsUnique();

                    b.ToTable("DocumentSettings", (string)null);
                });

            modelBuilder.Entity("RequestPigeon.Domain.Entities.LogApp", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("Event")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Info")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("LastModification")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("LogLevel")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ValueAfter")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("LogLevel");

                    b.HasIndex("UserId");

                    b.ToTable("LogApps", (string)null);
                });

            modelBuilder.Entity("RequestPigeon.Domain.Entities.LogDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(7)");

                    b.Property<Guid?>("DocumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Info")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("LastModification")
                        .HasColumnType("datetime2(7)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("StatusAfter")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("StatusBefore")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ValueAfter")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("WhatChanged")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("DocumentId");

                    b.HasIndex("UserId");

                    b.ToTable("LogDocuments", (string)null);
                });

            modelBuilder.Entity("RequestPigeon.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(7)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModification")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid?>("SuperiorRoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("SuperiorRoleId");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("RequestPigeon.Domain.Entities.RoleClaim", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClaimId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(7)");

                    b.Property<DateTime?>("LastModification")
                        .HasColumnType("datetime2(7)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("ClaimId");

                    b.HasIndex("RoleId", "ClaimId")
                        .IsUnique();

                    b.ToTable("RoleClaims", (string)null);
                });

            modelBuilder.Entity("RequestPigeon.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("Email")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("FailedLoginCount")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("IsActiveAccount")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsDemo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModification")
                        .HasColumnType("datetime2(7)");

                    b.Property<DateTime?>("LockedFailedLog")
                        .HasColumnType("datetime2(0)");

                    b.Property<bool>("LockedOut")
                        .HasColumnType("bit");

                    b.Property<bool>("PassChangeRequired")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Phone")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("RequestPigeon.Domain.Entities.UserClaim", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClaimId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(7)");

                    b.Property<DateTime?>("LastModification")
                        .HasColumnType("datetime2(7)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ClaimId");

                    b.HasIndex("UserId", "ClaimId")
                        .IsUnique();

                    b.ToTable("UserClaims", (string)null);
                });

            modelBuilder.Entity("RequestPigeon.Domain.Entities.BusinessTripRequestDocument", b =>
                {
                    b.HasBaseType("RequestPigeon.Domain.Entities.Document");

                    b.Property<decimal?>("AdvancePaymentAmount")
                        .HasPrecision(9, 2)
                        .HasColumnType("decimal(9,2)");

                    b.Property<string>("AdvancePaymentCurrency")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Country")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<DateOnly>("DateEnd")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DateStart")
                        .HasColumnType("date");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.HasIndex("Country");

                    b.HasIndex("DateStart");

                    b.HasIndex("Purpose");

                    b.ToTable("BusinessTripRequestDocuments", (string)null);
                });

            modelBuilder.Entity("RequestPigeon.Domain.Entities.CredentialsRequestDocument", b =>
                {
                    b.HasBaseType("RequestPigeon.Domain.Entities.Document");

                    b.Property<string>("Credential")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateOnly?>("ExpirationDate")
                        .HasColumnType("date");

                    b.ToTable("CredentialsRequestDocuments", (string)null);
                });

            modelBuilder.Entity("RequestPigeon.Domain.Entities.LeaveRequestDocument", b =>
                {
                    b.HasBaseType("RequestPigeon.Domain.Entities.Document");

                    b.Property<DateOnly>("DateEnd")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DateStart")
                        .HasColumnType("date");

                    b.Property<int>("Days")
                        .HasColumnType("int");

                    b.Property<string>("LeaveType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.HasIndex("LeaveType");

                    b.ToTable("LeaveRequestDocuments", (string)null);
                });

            modelBuilder.Entity("RequestPigeon.Domain.Entities.OtherRequestDocument", b =>
                {
                    b.HasBaseType("RequestPigeon.Domain.Entities.Document");

                    b.Property<DateOnly?>("AdditionalDate")
                        .HasColumnType("date");

                    b.Property<decimal?>("AmountFirst")
                        .HasPrecision(9, 2)
                        .HasColumnType("decimal(9,2)");

                    b.Property<decimal?>("AmountSecond")
                        .HasPrecision(9, 2)
                        .HasColumnType("decimal(9,2)");

                    b.Property<string>("TextAdditionalFieldOne")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("TextAdditionalFieldSecond")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("TextHeader")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.ToTable("OtherRequestDocuments", (string)null);
                });

            modelBuilder.Entity("RequestPigeon.Domain.Entities.PurchaseRequestDocument", b =>
                {
                    b.HasBaseType("RequestPigeon.Domain.Entities.Document");

                    b.Property<bool>("AccountantsRecorded")
                        .HasColumnType("bit");

                    b.Property<string>("ExpensesType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<decimal>("PlannedEstimatedCost")
                        .HasPrecision(9, 2)
                        .HasColumnType("decimal(9,2)");

                    b.Property<DateOnly?>("PlannedPurchaseDueDate")
                        .HasColumnType("date");

                    b.Property<decimal?>("RealCost")
                        .HasPrecision(9, 2)
                        .HasColumnType("decimal(9,2)");

                    b.Property<DateOnly?>("RealPurchaseDate")
                        .HasColumnType("date");

                    b.HasIndex("ExpensesType");

                    b.ToTable("PurchaseRequestDocuments", (string)null);
                });

            modelBuilder.Entity("RequestPigeon.Domain.Entities.RefundRequestDocument", b =>
                {
                    b.HasBaseType("RequestPigeon.Domain.Entities.Document");

                    b.Property<decimal>("Amount")
                        .HasPrecision(9, 2)
                        .HasColumnType("decimal(9,2)");

                    b.Property<string>("ExpensesType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<DateOnly>("PayDate")
                        .HasColumnType("date");

                    b.HasIndex("ExpensesType");

                    b.ToTable("RefundRequestDocuments", (string)null);
                });

            modelBuilder.Entity("RequestPigeon.Domain.Entities.Attachment", b =>
                {
                    b.HasOne("RequestPigeon.Domain.Entities.Document", "Document")
                        .WithMany("Attachments")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("RequestPigeon.Domain.Entities.DemoReseedLog", b =>
                {
                    b.HasOne("RequestPigeon.Domain.Entities.User", "StartedByUser")
                        .WithMany()
                        .HasForeignKey("StartedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("StartedByUser");
                });

            modelBuilder.Entity("RequestPigeon.Domain.Entities.Document", b =>
                {
                    b.HasOne("RequestPigeon.Domain.Entities.User", "Requester")
                        .WithMany("RequestedDocuments")
                        .HasForeignKey("RequesterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Requester");
                });

            modelBuilder.Entity("RequestPigeon.Domain.Entities.DocumentApprovalRule", b =>
                {
                    b.HasOne("RequestPigeon.Domain.Entities.DocumentSettings", "DocumentSettings")
                        .WithMany("ApprovalRules")
                        .HasForeignKey("DocumentSettingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RequestPigeon.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DocumentSettings");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RequestPigeon.Domain.Entities.DocumentApprovalStep", b =>
                {
                    b.HasOne("RequestPigeon.Domain.Entities.User", "Approver")
                        .WithMany("ApprovalSteps")
                        .HasForeignKey("ApproverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RequestPigeon.Domain.Entities.Document", "Document")
                        .WithMany("ApprovalSteps")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Approver");

                    b.Navigation("Document");
                });

            modelBuilder.Entity("RequestPigeon.Domain.Entities.LogApp", b =>
                {
                    b.HasOne("RequestPigeon.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("User");
                });

            modelBuilder.Entity("RequestPigeon.Domain.Entities.LogDocument", b =>
                {
                    b.HasOne("RequestPigeon.Domain.Entities.Document", "Document")
                        .WithMany("Logs")
                        .HasForeignKey("DocumentId");

                    b.HasOne("RequestPigeon.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Document");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RequestPigeon.Domain.Entities.Role", b =>
                {
                    b.HasOne("RequestPigeon.Domain.Entities.Role", "SuperiorRole")
                        .WithMany("SubordinateRoles")
                        .HasForeignKey("SuperiorRoleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("SuperiorRole");
                });

            modelBuilder.Entity("RequestPigeon.Domain.Entities.RoleClaim", b =>
                {
                    b.HasOne("RequestPigeon.Domain.Entities.Claim", "Claim")
                        .WithMany("RoleClaims")
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RequestPigeon.Domain.Entities.Role", "Role")
                        .WithMany("RoleClaims")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Claim");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("RequestPigeon.Domain.Entities.User", b =>
                {
                    b.HasOne("RequestPigeon.Domain.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("RequestPigeon.Domain.Entities.UserClaim", b =>
                {
                    b.HasOne("RequestPigeon.Domain.Entities.Claim", "Claim")
                        .WithMany("UserClaims")
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RequestPigeon.Domain.Entities.User", "User")
                        .WithMany("UserClaims")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Claim");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RequestPigeon.Domain.Entities.BusinessTripRequestDocument", b =>
                {
                    b.HasOne("RequestPigeon.Domain.Entities.Document", null)
                        .WithOne()
                        .HasForeignKey("RequestPigeon.Domain.Entities.BusinessTripRequestDocument", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RequestPigeon.Domain.Entities.CredentialsRequestDocument", b =>
                {
                    b.HasOne("RequestPigeon.Domain.Entities.Document", null)
                        .WithOne()
                        .HasForeignKey("RequestPigeon.Domain.Entities.CredentialsRequestDocument", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RequestPigeon.Domain.Entities.LeaveRequestDocument", b =>
                {
                    b.HasOne("RequestPigeon.Domain.Entities.Document", null)
                        .WithOne()
                        .HasForeignKey("RequestPigeon.Domain.Entities.LeaveRequestDocument", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RequestPigeon.Domain.Entities.OtherRequestDocument", b =>
                {
                    b.HasOne("RequestPigeon.Domain.Entities.Document", null)
                        .WithOne()
                        .HasForeignKey("RequestPigeon.Domain.Entities.OtherRequestDocument", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RequestPigeon.Domain.Entities.PurchaseRequestDocument", b =>
                {
                    b.HasOne("RequestPigeon.Domain.Entities.Document", null)
                        .WithOne()
                        .HasForeignKey("RequestPigeon.Domain.Entities.PurchaseRequestDocument", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RequestPigeon.Domain.Entities.RefundRequestDocument", b =>
                {
                    b.HasOne("RequestPigeon.Domain.Entities.Document", null)
                        .WithOne()
                        .HasForeignKey("RequestPigeon.Domain.Entities.RefundRequestDocument", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RequestPigeon.Domain.Entities.Claim", b =>
                {
                    b.Navigation("RoleClaims");

                    b.Navigation("UserClaims");
                });

            modelBuilder.Entity("RequestPigeon.Domain.Entities.Document", b =>
                {
                    b.Navigation("ApprovalSteps");

                    b.Navigation("Attachments");

                    b.Navigation("Logs");
                });

            modelBuilder.Entity("RequestPigeon.Domain.Entities.DocumentSettings", b =>
                {
                    b.Navigation("ApprovalRules");
                });

            modelBuilder.Entity("RequestPigeon.Domain.Entities.Role", b =>
                {
                    b.Navigation("RoleClaims");

                    b.Navigation("SubordinateRoles");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("RequestPigeon.Domain.Entities.User", b =>
                {
                    b.Navigation("ApprovalSteps");

                    b.Navigation("RequestedDocuments");

                    b.Navigation("UserClaims");
                });
#pragma warning restore 612, 618
        }
    }
}
